language: haxe

os:
  - linux
  - windows
  
haxe:
 - development
 
install:
 - yes | haxelib install hxcpp
 - yes | haxelib install lime
 - yes | haxelib install openfl
 - yes | haxelib install actuate
 - yes | haxelib install svg
 - yes | haxelib install hscript
 - yes | haxelib install format
 - yes | haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

script:
 - haxelib run lime build cpp