language: haxe

os:
  - linux

haxe:
 - development
 
install:
 - yes | haxelib install hxcpp
 - yes | haxelib install lime
 - yes | haxelib install openfl
 - yes | haxelib install actuate
 - yes | haxelib install svg
 - yes | haxelib install hscript
 - yes | haxelib install format
 - yes | haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
 - yes | haxelib install hxp https://github.com/openfl/hxp

script:
 - haxelib run lime build cpp