version: 2
jobs:
  
  build:
    docker:
     - image: openfl/openfl-tests-unit-3.4:0.0.3
    steps:
     - checkout
     #libs
     - run: haxelib install hxcpp
     - run: haxelib install actuate
     - run: haxelib install hscript
     - run: haxelib install format
     - run: haxelib install openfl
     - run: haxelib install lime
     - run: haxelib dev format
     #run
     - run: haxelib run lime build all neko
     - run: haxelib run lime build all cpp
  
workflows:
  version: 2
  build:
    jobs:
     - build